org.gradle.jvmargs=-Xms128m -Xmx2g -XX:MaxMetaspaceSize=384m -XX:ReservedCodeCacheSize=96m -XX:CompressedClassSpaceSize=128m -XX:+UseSerialGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20
org.gradle.daemon=false
org.gradle.workers.max=1
org.gradle.vfs.watch=false

kotlin.compiler.execution.strategy=in-process
kotlin.daemon.jvmargs=-Xmx256M -XX:MaxMetaspaceSize=256m -XX:ReservedCodeCacheSize=96m

minecraft_version=1.20.1
mc_version=1.20.1
minecraft_version_range=[1.20.1,1.21)

forge_version=47.4.23
forge_version_range=[47,)

loader_version_range=[47,)

mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

mod_id=gtetcore
mod_name=GTEternalTime -- core
mod_license=LGPL-3.0
mod_version=0.0.1
mod_group_id=rain
mod_authors=RainFoxStar
mod_description=

gtm_version=7.5.3
configuration_version=2.2.0
jei_version=15.20.0.132
emi_version=1.1.24+1.20.1

